language: node_js
node_js:
- node
- lts/carbon
- lts/boron
sudo: false
env:
  global:
    secure: OIN8IWAmpeo7Gp/MF0zizjhWYUag1tJek0yt8DGmq99nI1vIvy6pxj+uey4iSGLwulAE/p59OC9MNt0K+Er+R4Zkb3D7ACSYTQztltB2X7tYTvFptV4tbzQkiwgJIiBeCVD7vJoTDoFmJpkX4bv5qjquCwiDcVYoSiQEWZkP5kQ=
before_install:
- if [[ `npm -v` != 6* ]]; then npm install -g npm; fi
- npm install -g greenkeeper-lockfile@1
install:
- if [[ $TRAVIS_BRANCH == greenkeeper/* ]] && [[ -v TRAVIS_COMMIT_RANGE ]]; then npm install; else npm ci; fi
before_script: greenkeeper-lockfile-update
script:
- npm run lint
- npm run build
- npm test
after_script: greenkeeper-lockfile-upload
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- git checkout -- .
- npm run clean
- npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: egy186@yahoo.co.jp
  api_key:
    secure: KKqoz7TDoO2mIVmcV/puyrMHZCTCDbXrsj0Tkled8l+BCp7DthbwPtiohXfnARSIpt7/XxAPoMvSqMD5qB2qlGCRxs9oFeta3kiakhr/ynCZi3f2kccN/pv/RKrkFVgVVixr59lgzDC7VuZDY+nti548nMeY3zkebcfjz9ZbzUA=
  on:
    all_branches: true
    repo: egy186/icojs
    tags: true
