language: node_js
node_js:
- '5'
- '4'
sudo: false
before_script:
- npm install -g gulp
script:
- npm run lint
- npm test
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: egy186@yahoo.co.jp
  api_key:
    secure: KKqoz7TDoO2mIVmcV/puyrMHZCTCDbXrsj0Tkled8l+BCp7DthbwPtiohXfnARSIpt7/XxAPoMvSqMD5qB2qlGCRxs9oFeta3kiakhr/ynCZi3f2kccN/pv/RKrkFVgVVixr59lgzDC7VuZDY+nti548nMeY3zkebcfjz9ZbzUA=
  on:
    tags: true
    repo: egy186/icojs
